<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Bus;
use Carbon\Carbon;

class BusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fechaReferencia = Carbon::create(2024, 12, 1);

        $buses = [
            // ============================================
            // BUSES CLÁSICOS (1 piso, servicio básico)
            // Factor tarifa: 1.0x (tarifa base)
            // Capacidad: 45 pasajeros
            // ============================================
            [
                'patente' => 'BCHV12',
                'patente_verificador' => '3',
                'marca' => 'Mercedes-Benz',
                'modelo' => 'OF-1721',
                'anio' => 2018,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'MB18CL001',
                'numero_motor' => 'OM906001',
                'numero_chasis' => 'CH18001',
                'capacidad_pasajeros' => 45,
                'tipo_bus' => 'simple',
                'tipo_servicio' => 'clasico',
                'factor_tarifa' => 1.0,
                'cantidad_ejes' => '2',
                'marca_motor' => 'Mercedes-Benz',
                'modelo_motor' => 'OM-906',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Mercedes-Benz',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Viaggio',
                'fecha_adquisicion' => '2018-03-15',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(3),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(9),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(6),
                'numero_soap' => 'SOAP2024001',
                'compania_seguro' => 'HDI Seguros',
                'numero_poliza' => 'POL2024001',
                'tipo_cobertura_adicional' => 'terceros',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(8),
                'numero_permiso_circulacion' => 'PC2024001',
                'kilometraje_original' => 125000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subMonths(2),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonth(),
            ],
            [
                'patente' => 'DGTY45',
                'patente_verificador' => '7',
                'marca' => 'Volvo',
                'modelo' => 'B7R',
                'anio' => 2019,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'VLV19CL002',
                'numero_motor' => 'D11002',
                'numero_chasis' => 'CH19002',
                'capacidad_pasajeros' => 45,
                'tipo_bus' => 'simple',
                'tipo_servicio' => 'clasico',
                'factor_tarifa' => 1.0,
                'cantidad_ejes' => '2',
                'marca_motor' => 'Volvo',
                'modelo_motor' => 'D11',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Volvo',
                'marca_carroceria' => 'Caio',
                'modelo_carroceria' => 'Apache Vip',
                'fecha_adquisicion' => '2019-06-20',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(4),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(8),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(5),
                'numero_soap' => 'SOAP2024002',
                'compania_seguro' => 'Mapfre',
                'numero_poliza' => 'POL2024002',
                'tipo_cobertura_adicional' => 'terceros',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(7),
                'numero_permiso_circulacion' => 'PC2024002',
                'kilometraje_original' => 95000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subMonths(1),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(2),
            ],
            [
                'patente' => 'FFRT89',
                'patente_verificador' => '2',
                'marca' => 'Scania',
                'modelo' => 'K310',
                'anio' => 2020,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'SCN20CL003',
                'numero_motor' => 'DC13003',
                'numero_chasis' => 'CH20003',
                'capacidad_pasajeros' => 45,
                'tipo_bus' => 'simple',
                'tipo_servicio' => 'clasico',
                'factor_tarifa' => 1.0,
                'cantidad_ejes' => '2',
                'marca_motor' => 'Scania',
                'modelo_motor' => 'DC13',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Scania',
                'marca_carroceria' => 'Metalpar',
                'modelo_carroceria' => 'Tronador',
                'fecha_adquisicion' => '2020-01-10',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(5),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(7),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(6),
                'numero_soap' => 'SOAP2024003',
                'compania_seguro' => 'Liberty Seguros',
                'numero_poliza' => 'POL2024003',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(9),
                'numero_permiso_circulacion' => 'PC2024003',
                'kilometraje_original' => 68000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subWeeks(3),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(2),
            ],

            // ============================================
            // BUSES SEMICAMA (2 pisos, asientos reclinables)
            // Factor tarifa: 1.4x (40% más caro)
            // Capacidad: 38 pasajeros
            // ============================================
            [
                'patente' => 'HJKL23',
                'patente_verificador' => '5',
                'marca' => 'Mercedes-Benz',
                'modelo' => 'O-500R',
                'anio' => 2020,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'MB20SC001',
                'numero_motor' => 'OM457001',
                'numero_chasis' => 'CH20SC001',
                'capacidad_pasajeros' => 38,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'semicama',
                'factor_tarifa' => 1.4,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Mercedes-Benz',
                'modelo_motor' => 'OM-457',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Mercedes-Benz',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1200',
                'fecha_adquisicion' => '2020-08-15',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(3),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(9),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(7),
                'numero_soap' => 'SOAP2024004',
                'compania_seguro' => 'HDI Seguros',
                'numero_poliza' => 'POL2024004',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(10),
                'numero_permiso_circulacion' => 'PC2024004',
                'kilometraje_original' => 82000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subMonths(1),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(2),
            ],
            [
                'patente' => 'PLMN67',
                'patente_verificador' => '1',
                'marca' => 'Volvo',
                'modelo' => 'B12M',
                'anio' => 2021,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'VLV21SC002',
                'numero_motor' => 'D13002',
                'numero_chasis' => 'CH21SC002',
                'capacidad_pasajeros' => 38,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'semicama',
                'factor_tarifa' => 1.4,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Volvo',
                'modelo_motor' => 'D13',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Volvo',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1200',
                'fecha_adquisicion' => '2021-02-28',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(4),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(8),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(6),
                'numero_soap' => 'SOAP2024005',
                'compania_seguro' => 'Mapfre',
                'numero_poliza' => 'POL2024005',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(8),
                'numero_permiso_circulacion' => 'PC2024005',
                'kilometraje_original' => 54000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subWeeks(2),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(3),
            ],
            [
                'patente' => 'QRST90',
                'patente_verificador' => '4',
                'marca' => 'Scania',
                'modelo' => 'K380',
                'anio' => 2021,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'SCN21SC003',
                'numero_motor' => 'DC13SC003',
                'numero_chasis' => 'CH21SC003',
                'capacidad_pasajeros' => 38,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'semicama',
                'factor_tarifa' => 1.4,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Scania',
                'modelo_motor' => 'DC13',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Scania',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1200',
                'fecha_adquisicion' => '2021-09-12',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(5),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(7),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(8),
                'numero_soap' => 'SOAP2024006',
                'compania_seguro' => 'Liberty Seguros',
                'numero_poliza' => 'POL2024006',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(11),
                'numero_permiso_circulacion' => 'PC2024006',
                'kilometraje_original' => 41000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subWeeks(4),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(2),
            ],

            // ============================================
            // BUSES CAMA (2 pisos, asientos 180°)
            // Factor tarifa: 2.0x (el doble de la tarifa base)
            // Capacidad: 32 pasajeros
            // ============================================
            [
                'patente' => 'UVWX34',
                'patente_verificador' => '6',
                'marca' => 'Mercedes-Benz',
                'modelo' => 'O-500RS',
                'anio' => 2022,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'MB22CM001',
                'numero_motor' => 'OM457CM001',
                'numero_chasis' => 'CH22CM001',
                'capacidad_pasajeros' => 32,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'cama',
                'factor_tarifa' => 2.0,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Mercedes-Benz',
                'modelo_motor' => 'OM-457',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Mercedes-Benz',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1800',
                'fecha_adquisicion' => '2022-04-20',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(6),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(6),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(9),
                'numero_soap' => 'SOAP2024007',
                'compania_seguro' => 'HDI Seguros',
                'numero_poliza' => 'POL2024007',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addYear(),
                'numero_permiso_circulacion' => 'PC2024007',
                'kilometraje_original' => 28000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subWeeks(1),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(3),
            ],
            [
                'patente' => 'YZAB56',
                'patente_verificador' => '8',
                'marca' => 'Volvo',
                'modelo' => 'B340M',
                'anio' => 2022,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'VLV22CM002',
                'numero_motor' => 'D13CM002',
                'numero_chasis' => 'CH22CM002',
                'capacidad_pasajeros' => 32,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'cama',
                'factor_tarifa' => 2.0,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Volvo',
                'modelo_motor' => 'D13',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Volvo',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1800',
                'fecha_adquisicion' => '2022-10-15',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(7),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(5),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(10),
                'numero_soap' => 'SOAP2024008',
                'compania_seguro' => 'Mapfre',
                'numero_poliza' => 'POL2024008',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addYear(),
                'numero_permiso_circulacion' => 'PC2024008',
                'kilometraje_original' => 15000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subDays(10),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(3),
            ],

            // ============================================
            // BUSES PREMIUM (2 pisos, servicio lujo)
            // Factor tarifa: 3.0x (triple de la tarifa base)
            // Capacidad: 20 pasajeros
            // ============================================
            [
                'patente' => 'CDEF78',
                'patente_verificador' => '9',
                'marca' => 'Mercedes-Benz',
                'modelo' => 'O-500RS',
                'anio' => 2023,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'MB23PR001',
                'numero_motor' => 'OM457PR001',
                'numero_chasis' => 'CH23PR001',
                'capacidad_pasajeros' => 20,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'premium',
                'factor_tarifa' => 3.0,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Mercedes-Benz',
                'modelo_motor' => 'OM-457',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Mercedes-Benz',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1800',
                'fecha_adquisicion' => '2023-05-30',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(8),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(4),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(11),
                'numero_soap' => 'SOAP2024009',
                'compania_seguro' => 'HDI Seguros',
                'numero_poliza' => 'POL2024009',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(13),
                'numero_permiso_circulacion' => 'PC2024009',
                'kilometraje_original' => 8200,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subWeeks(2),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(4),
            ],
            [
                'patente' => 'GHIJ01',
                'patente_verificador' => 'K',
                'marca' => 'Volvo',
                'modelo' => 'B340M',
                'anio' => 2023,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'VLV23PR002',
                'numero_motor' => 'D13PR002',
                'numero_chasis' => 'CH23PR002',
                'capacidad_pasajeros' => 20,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'premium',
                'factor_tarifa' => 3.0,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Volvo',
                'modelo_motor' => 'D13',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Volvo',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1800',
                'fecha_adquisicion' => '2023-11-25',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(9),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(3),
                'vencimiento_soap' => $fechaReferencia->copy()->addYear(),
                'numero_soap' => 'SOAP2024010',
                'compania_seguro' => 'Liberty Seguros',
                'numero_poliza' => 'POL2024010',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(14),
                'numero_permiso_circulacion' => 'PC2024010',
                'kilometraje_original' => 3200,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subDays(2),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(4),
            ],

            // ============================================
            // BUSES ADICIONALES (mix para tener variedad)
            // ============================================
            [
                'patente' => 'KLMN23',
                'patente_verificador' => '0',
                'marca' => 'Scania',
                'modelo' => 'K340',
                'anio' => 2019,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'SCN19CL004',
                'numero_motor' => 'DC13CL004',
                'numero_chasis' => 'CH19CL004',
                'capacidad_pasajeros' => 45,
                'tipo_bus' => 'simple',
                'tipo_servicio' => 'clasico',
                'factor_tarifa' => 1.0,
                'cantidad_ejes' => '2',
                'marca_motor' => 'Scania',
                'modelo_motor' => 'DC13',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Scania',
                'marca_carroceria' => 'Metalpar',
                'modelo_carroceria' => 'Pucará',
                'fecha_adquisicion' => '2019-11-05',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(2),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(10),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(4),
                'numero_soap' => 'SOAP2024011',
                'compania_seguro' => 'Mapfre',
                'numero_poliza' => 'POL2024011',
                'tipo_cobertura_adicional' => 'terceros',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(6),
                'numero_permiso_circulacion' => 'PC2024011',
                'kilometraje_original' => 112000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subMonths(3),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addWeeks(2),
            ],
            [
                'patente' => 'OPQR45',
                'patente_verificador' => '2',
                'marca' => 'Mercedes-Benz',
                'modelo' => 'O-500R',
                'anio' => 2021,
                'tipo_combustible' => 'diesel',
                'numero_serie' => 'MB21SC004',
                'numero_motor' => 'OM457SC004',
                'numero_chasis' => 'CH21SC004',
                'capacidad_pasajeros' => 38,
                'tipo_bus' => 'doble_piso',
                'tipo_servicio' => 'semicama',
                'factor_tarifa' => 1.4,
                'cantidad_ejes' => '3',
                'marca_motor' => 'Mercedes-Benz',
                'modelo_motor' => 'OM-457',
                'ubicacion_motor' => 'trasero',
                'marca_chasis' => 'Mercedes-Benz',
                'marca_carroceria' => 'Marcopolo',
                'modelo_carroceria' => 'Paradiso 1200',
                'fecha_adquisicion' => '2021-07-18',
                'estado' => 'operativo',
                'proxima_revision_tecnica' => $fechaReferencia->copy()->addMonths(3),
                'ultima_revision_tecnica' => $fechaReferencia->copy()->subMonths(9),
                'vencimiento_soap' => $fechaReferencia->copy()->addMonths(7),
                'numero_soap' => 'SOAP2024012',
                'compania_seguro' => 'HDI Seguros',
                'numero_poliza' => 'POL2024012',
                'tipo_cobertura_adicional' => 'full',
                'vencimiento_poliza' => $fechaReferencia->copy()->addMonths(9),
                'numero_permiso_circulacion' => 'PC2024012',
                'kilometraje_original' => 62000,
                'proximo_mantenimiento_km' => 10000,
                'fecha_ultimo_mantenimiento' => $fechaReferencia->copy()->subMonths(2),
                'fecha_proximo_mantenimiento' => $fechaReferencia->copy()->addMonths(1),
            ],
        ];

        foreach ($buses as $busData) {
            Bus::create($busData);
        }

        $this->command->info('✅ 12 buses creados con tipos de servicio: 4 Clásicos, 4 Semicama, 2 Cama, 2 Premium');
    }
}